# Generate a comprehensive seed dataset:
# - 2010-2023 coverage for major players
# - college field added
# - enough cross-team history that players genuinely connect

import pandas as pd, os

# (player_id, name, position, college, team, year)
# Covering real career histories so the graph is well-connected across coaching trees

roster_data = [
    # ─── BILL BELICHICK ERA — NEW ENGLAND ───────────────────────────────────
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2001),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2002),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2003),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2004),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2005),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2006),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2007),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2008),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2009),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2010),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2011),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2012),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2013),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2014),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2015),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2016),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2017),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "NWE", 2018),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "TAM", 2020),
    ("bradyt-01",    "Tom Brady",           "QB",  "Michigan",          "TAM", 2021),
    ("gronkr-01",    "Rob Gronkowski",      "TE",  "Arizona",           "NWE", 2010),
    ("gronkr-01",    "Rob Gronkowski",      "TE",  "Arizona",           "NWE", 2011),
    ("gronkr-01",    "Rob Gronkowski",      "TE",  "Arizona",           "NWE", 2012),
    ("gronkr-01",    "Rob Gronkowski",      "TE",  "Arizona",           "NWE", 2013),
    ("gronkr-01",    "Rob Gronkowski",      "TE",  "Arizona",           "NWE", 2014),
    ("gronkr-01",    "Rob Gronkowski",      "TE",  "Arizona",           "NWE", 2015),
    ("gronkr-01",    "Rob Gronkowski",      "TE",  "Arizona",           "NWE", 2016),
    ("gronkr-01",    "Rob Gronkowski",      "TE",  "Arizona",           "NWE", 2017),
    ("gronkr-01",    "Rob Gronkowski",      "TE",  "Arizona",           "NWE", 2018),
    ("gronkr-01",    "Rob Gronkowski",      "TE",  "Arizona",           "TAM", 2020),
    ("gronkr-01",    "Rob Gronkowski",      "TE",  "Arizona",           "TAM", 2021),
    ("gronkr-01",    "Rob Gronkowski",      "TE",  "Arizona",           "RAM", 2022),
    ("edelj-01",     "Julian Edelman",      "WR",  "Kent State",        "NWE", 2009),
    ("edelj-01",     "Julian Edelman",      "WR",  "Kent State",        "NWE", 2010),
    ("edelj-01",     "Julian Edelman",      "WR",  "Kent State",        "NWE", 2011),
    ("edelj-01",     "Julian Edelman",      "WR",  "Kent State",        "NWE", 2013),
    ("edelj-01",     "Julian Edelman",      "WR",  "Kent State",        "NWE", 2014),
    ("edelj-01",     "Julian Edelman",      "WR",  "Kent State",        "NWE", 2015),
    ("edelj-01",     "Julian Edelman",      "WR",  "Kent State",        "NWE", 2016),
    ("edelj-01",     "Julian Edelman",      "WR",  "Kent State",        "NWE", 2017),
    ("edelj-01",     "Julian Edelman",      "WR",  "Kent State",        "NWE", 2018),
    ("mccod-01",     "Devin McCourty",      "DB",  "Rutgers",           "NWE", 2010),
    ("mccod-01",     "Devin McCourty",      "DB",  "Rutgers",           "NWE", 2011),
    ("mccod-01",     "Devin McCourty",      "DB",  "Rutgers",           "NWE", 2012),
    ("mccod-01",     "Devin McCourty",      "DB",  "Rutgers",           "NWE", 2013),
    ("mccod-01",     "Devin McCourty",      "DB",  "Rutgers",           "NWE", 2014),
    ("mccod-01",     "Devin McCourty",      "DB",  "Rutgers",           "NWE", 2015),
    ("mccod-01",     "Devin McCourty",      "DB",  "Rutgers",           "NWE", 2016),
    ("mccod-01",     "Devin McCourty",      "DB",  "Rutgers",           "NWE", 2017),
    ("mccod-01",     "Devin McCourty",      "DB",  "Rutgers",           "NWE", 2018),
    ("mccod-01",     "Devin McCourty",      "DB",  "Rutgers",           "NWE", 2019),
    ("mccod-01",     "Devin McCourty",      "DB",  "Rutgers",           "NWE", 2020),
    ("mccod-01",     "Devin McCourty",      "DB",  "Rutgers",           "NWE", 2021),
    ("mccod-01",     "Devin McCourty",      "DB",  "Rutgers",           "NWE", 2022),
    ("dorsettph-01", "Phillip Dorsett",     "WR",  "Miami (FL)",        "CIN", 2015),   # drafted CIN
    ("dorsettph-01", "Phillip Dorsett",     "WR",  "Miami (FL)",        "CIN", 2016),
    ("dorsettph-01", "Phillip Dorsett",     "WR",  "Miami (FL)",        "NWE", 2017),
    ("dorsettph-01", "Phillip Dorsett",     "WR",  "Miami (FL)",        "NWE", 2018),
    # Belichick disciple — Josh McDaniels (OC) became HC at Raiders
    ("carrd-01",     "Derek Carr",          "QB",  "Fresno State",      "RAI", 2014),
    ("carrd-01",     "Derek Carr",          "QB",  "Fresno State",      "RAI", 2015),
    ("carrd-01",     "Derek Carr",          "QB",  "Fresno State",      "RAI", 2016),
    ("carrd-01",     "Derek Carr",          "QB",  "Fresno State",      "RAI", 2017),
    ("carrd-01",     "Derek Carr",          "QB",  "Fresno State",      "RAI", 2018),
    ("carrd-01",     "Derek Carr",          "QB",  "Fresno State",      "RAI", 2019),
    ("carrd-01",     "Derek Carr",          "QB",  "Fresno State",      "RAI", 2020),
    ("carrd-01",     "Derek Carr",          "QB",  "Fresno State",      "RAI", 2021),
    ("carrd-01",     "Derek Carr",          "QB",  "Fresno State",      "RAI", 2022),
    ("jacobj-01",    "Josh Jacobs",         "RB",  "Alabama",           "RAI", 2019),
    ("jacobj-01",    "Josh Jacobs",         "RB",  "Alabama",           "RAI", 2020),
    ("jacobj-01",    "Josh Jacobs",         "RB",  "Alabama",           "RAI", 2021),
    ("jacobj-01",    "Josh Jacobs",         "RB",  "Alabama",           "RAI", 2022),
    ("jacobj-01",    "Josh Jacobs",         "RB",  "Alabama",           "KAN", 2023),  # Bridge: RAI→KAN
    ("walledr-01",   "Darren Waller",       "TE",  "Georgia Tech",      "RAI", 2018),
    ("walledr-01",   "Darren Waller",       "TE",  "Georgia Tech",      "RAI", 2019),
    ("walledr-01",   "Darren Waller",       "TE",  "Georgia Tech",      "RAI", 2020),
    ("walledr-01",   "Darren Waller",       "TE",  "Georgia Tech",      "RAI", 2021),
    ("walledr-01",   "Darren Waller",       "TE",  "Georgia Tech",      "NYG", 2023),
    # Matt Patricia (Belichick DC) → Detroit Lions HC
    ("goffj-01",     "Jared Goff",          "QB",  "California",        "RAM", 2016),
    ("goffj-01",     "Jared Goff",          "QB",  "California",        "RAM", 2017),
    ("goffj-01",     "Jared Goff",          "QB",  "California",        "RAM", 2018),
    ("goffj-01",     "Jared Goff",          "QB",  "California",        "RAM", 2019),
    ("goffj-01",     "Jared Goff",          "QB",  "California",        "DET", 2021),
    ("goffj-01",     "Jared Goff",          "QB",  "California",        "DET", 2022),
    ("goffj-01",     "Jared Goff",          "QB",  "California",        "DET", 2023),
    ("swiftd-01",    "D'Andre Swift",       "RB",  "Georgia",           "DET", 2020),
    ("swiftd-01",    "D'Andre Swift",       "RB",  "Georgia",           "DET", 2021),
    ("swiftd-01",    "D'Andre Swift",       "RB",  "Georgia",           "DET", 2022),
    ("swiftd-01",    "D'Andre Swift",       "RB",  "Georgia",           "PHI", 2023),  # Bridge: DET→PHI
    ("stbroa-01",    "Amon-Ra St. Brown",   "WR",  "USC",               "DET", 2021),
    ("stbroa-01",    "Amon-Ra St. Brown",   "WR",  "USC",               "DET", 2022),
    ("stbroa-01",    "Amon-Ra St. Brown",   "WR",  "USC",               "DET", 2023),
    ("sewell-01",    "Penei Sewell",        "OT",  "Oregon",            "DET", 2021),
    ("sewell-01",    "Penei Sewell",        "OT",  "Oregon",            "DET", 2022),
    ("sewell-01",    "Penei Sewell",        "OT",  "Oregon",            "DET", 2023),

    # ─── ANDY REID ERA — KANSAS CITY CHIEFS ─────────────────────────────────
    ("mahomesp-01",  "Patrick Mahomes",     "QB",  "Texas Tech",        "KAN", 2017),
    ("mahomesp-01",  "Patrick Mahomes",     "QB",  "Texas Tech",        "KAN", 2018),
    ("mahomesp-01",  "Patrick Mahomes",     "QB",  "Texas Tech",        "KAN", 2019),
    ("mahomesp-01",  "Patrick Mahomes",     "QB",  "Texas Tech",        "KAN", 2020),
    ("mahomesp-01",  "Patrick Mahomes",     "QB",  "Texas Tech",        "KAN", 2021),
    ("mahomesp-01",  "Patrick Mahomes",     "QB",  "Texas Tech",        "KAN", 2022),
    ("mahomesp-01",  "Patrick Mahomes",     "QB",  "Texas Tech",        "KAN", 2023),
    ("kelcet-01",    "Travis Kelce",        "TE",  "Cincinnati",        "KAN", 2013),
    ("kelcet-01",    "Travis Kelce",        "TE",  "Cincinnati",        "KAN", 2014),
    ("kelcet-01",    "Travis Kelce",        "TE",  "Cincinnati",        "KAN", 2015),
    ("kelcet-01",    "Travis Kelce",        "TE",  "Cincinnati",        "KAN", 2016),
    ("kelcet-01",    "Travis Kelce",        "TE",  "Cincinnati",        "KAN", 2017),
    ("kelcet-01",    "Travis Kelce",        "TE",  "Cincinnati",        "KAN", 2018),
    ("kelcet-01",    "Travis Kelce",        "TE",  "Cincinnati",        "KAN", 2019),
    ("kelcet-01",    "Travis Kelce",        "TE",  "Cincinnati",        "KAN", 2020),
    ("kelcet-01",    "Travis Kelce",        "TE",  "Cincinnati",        "KAN", 2021),
    ("kelcet-01",    "Travis Kelce",        "TE",  "Cincinnati",        "KAN", 2022),
    ("kelcet-01",    "Travis Kelce",        "TE",  "Cincinnati",        "KAN", 2023),
    ("hillet-01",    "Tyreek Hill",         "WR",  "West Alabama",      "KAN", 2016),
    ("hillet-01",    "Tyreek Hill",         "WR",  "West Alabama",      "KAN", 2017),
    ("hillet-01",    "Tyreek Hill",         "WR",  "West Alabama",      "KAN", 2018),
    ("hillet-01",    "Tyreek Hill",         "WR",  "West Alabama",      "KAN", 2019),
    ("hillet-01",    "Tyreek Hill",         "WR",  "West Alabama",      "KAN", 2020),
    ("hillet-01",    "Tyreek Hill",         "WR",  "West Alabama",      "KAN", 2021),
    ("hillet-01",    "Tyreek Hill",         "WR",  "West Alabama",      "MIA", 2022),  # Key bridge
    ("hillet-01",    "Tyreek Hill",         "WR",  "West Alabama",      "MIA", 2023),
    ("jonesc-01",    "Chris Jones",         "DT",  "Mississippi State", "KAN", 2016),
    ("jonesc-01",    "Chris Jones",         "DT",  "Mississippi State", "KAN", 2017),
    ("jonesc-01",    "Chris Jones",         "DT",  "Mississippi State", "KAN", 2018),
    ("jonesc-01",    "Chris Jones",         "DT",  "Mississippi State", "KAN", 2019),
    ("jonesc-01",    "Chris Jones",         "DT",  "Mississippi State", "KAN", 2020),
    ("jonesc-01",    "Chris Jones",         "DT",  "Mississippi State", "KAN", 2021),
    ("jonesc-01",    "Chris Jones",         "DT",  "Mississippi State", "KAN", 2022),
    ("jonesc-01",    "Chris Jones",         "DT",  "Mississippi State", "KAN", 2023),
    ("hardmanm-01",  "Mecole Hardman",      "WR",  "Georgia",           "KAN", 2019),
    ("hardmanm-01",  "Mecole Hardman",      "WR",  "Georgia",           "KAN", 2020),
    ("hardmanm-01",  "Mecole Hardman",      "WR",  "Georgia",           "KAN", 2021),
    ("hardmanm-01",  "Mecole Hardman",      "WR",  "Georgia",           "NYJ", 2022),  # Bridge: KAN→NYJ
    ("hardmanm-01",  "Mecole Hardman",      "WR",  "Georgia",           "KAN", 2023),
    # Alex Smith (Reid QB before Mahomes) - bridges to other teams/coaches
    ("smitha-01",    "Alex Smith",          "QB",  "Utah",              "SFO", 2005),
    ("smitha-01",    "Alex Smith",          "QB",  "Utah",              "SFO", 2006),
    ("smitha-01",    "Alex Smith",          "QB",  "Utah",              "SFO", 2011),
    ("smitha-01",    "Alex Smith",          "QB",  "Utah",              "SFO", 2012),
    ("smitha-01",    "Alex Smith",          "QB",  "Utah",              "KAN", 2013),
    ("smitha-01",    "Alex Smith",          "QB",  "Utah",              "KAN", 2014),
    ("smitha-01",    "Alex Smith",          "QB",  "Utah",              "KAN", 2015),
    ("smitha-01",    "Alex Smith",          "QB",  "Utah",              "KAN", 2016),
    ("smitha-01",    "Alex Smith",          "QB",  "Utah",              "KAN", 2017),
    ("smitha-01",    "Alex Smith",          "QB",  "Utah",              "WAS", 2018),
    # Nick Sirianni (Reid disciple) → Philadelphia Eagles
    ("hurtsj-01",    "Jalen Hurts",         "QB",  "Alabama/Oklahoma",  "PHI", 2020),
    ("hurtsj-01",    "Jalen Hurts",         "QB",  "Alabama/Oklahoma",  "PHI", 2021),
    ("hurtsj-01",    "Jalen Hurts",         "QB",  "Alabama/Oklahoma",  "PHI", 2022),
    ("hurtsj-01",    "Jalen Hurts",         "QB",  "Alabama/Oklahoma",  "PHI", 2023),
    ("brownaj-01",   "A.J. Brown",          "WR",  "Ole Miss",          "TEN", 2019),
    ("brownaj-01",   "A.J. Brown",          "WR",  "Ole Miss",          "TEN", 2020),
    ("brownaj-01",   "A.J. Brown",          "WR",  "Ole Miss",          "TEN", 2021),
    ("brownaj-01",   "A.J. Brown",          "WR",  "Ole Miss",          "PHI", 2022),  # Bridge TEN→PHI
    ("brownaj-01",   "A.J. Brown",          "WR",  "Ole Miss",          "PHI", 2023),
    ("smithd-01",    "DeVonta Smith",       "WR",  "Alabama",           "PHI", 2021),
    ("smithd-01",    "DeVonta Smith",       "WR",  "Alabama",           "PHI", 2022),
    ("smithd-01",    "DeVonta Smith",       "WR",  "Alabama",           "PHI", 2023),

    # ─── BRUCE ARIANS / TODD BOWLES — TAMPA BAY ─────────────────────────────
    ("evansm-01",    "Mike Evans",          "WR",  "Texas A&M",         "TAM", 2014),
    ("evansm-01",    "Mike Evans",          "WR",  "Texas A&M",         "TAM", 2015),
    ("evansm-01",    "Mike Evans",          "WR",  "Texas A&M",         "TAM", 2016),
    ("evansm-01",    "Mike Evans",          "WR",  "Texas A&M",         "TAM", 2017),
    ("evansm-01",    "Mike Evans",          "WR",  "Texas A&M",         "TAM", 2018),
    ("evansm-01",    "Mike Evans",          "WR",  "Texas A&M",         "TAM", 2019),
    ("evansm-01",    "Mike Evans",          "WR",  "Texas A&M",         "TAM", 2020),
    ("evansm-01",    "Mike Evans",          "WR",  "Texas A&M",         "TAM", 2021),
    ("evansm-01",    "Mike Evans",          "WR",  "Texas A&M",         "TAM", 2022),
    ("evansm-01",    "Mike Evans",          "WR",  "Texas A&M",         "TAM", 2023),
    ("godwinc-01",   "Chris Godwin",        "WR",  "Penn State",        "TAM", 2017),
    ("godwinc-01",   "Chris Godwin",        "WR",  "Penn State",        "TAM", 2018),
    ("godwinc-01",   "Chris Godwin",        "WR",  "Penn State",        "TAM", 2019),
    ("godwinc-01",   "Chris Godwin",        "WR",  "Penn State",        "TAM", 2020),
    ("godwinc-01",   "Chris Godwin",        "WR",  "Penn State",        "TAM", 2021),
    ("godwinc-01",   "Chris Godwin",        "WR",  "Penn State",        "TAM", 2022),
    ("wirfst-01",    "Tristan Wirfs",       "OT",  "Iowa",              "TAM", 2020),
    ("wirfst-01",    "Tristan Wirfs",       "OT",  "Iowa",              "TAM", 2021),
    ("wirfst-01",    "Tristan Wirfs",       "OT",  "Iowa",              "TAM", 2022),
    ("wirfst-01",    "Tristan Wirfs",       "OT",  "Iowa",              "TAM", 2023),
    ("whited-01",    "Devin White",         "LB",  "LSU",               "TAM", 2019),
    ("whited-01",    "Devin White",         "LB",  "LSU",               "TAM", 2020),
    ("whited-01",    "Devin White",         "LB",  "LSU",               "TAM", 2021),
    ("whited-01",    "Devin White",         "LB",  "LSU",               "TAM", 2022),

    # ─── SEAN McVAY — LOS ANGELES RAMS ──────────────────────────────────────
    ("staffordm-01", "Matthew Stafford",    "QB",  "Georgia",           "DET", 2009),
    ("staffordm-01", "Matthew Stafford",    "QB",  "Georgia",           "DET", 2010),
    ("staffordm-01", "Matthew Stafford",    "QB",  "Georgia",           "DET", 2011),
    ("staffordm-01", "Matthew Stafford",    "QB",  "Georgia",           "DET", 2012),
    ("staffordm-01", "Matthew Stafford",    "QB",  "Georgia",           "DET", 2013),
    ("staffordm-01", "Matthew Stafford",    "QB",  "Georgia",           "DET", 2014),
    ("staffordm-01", "Matthew Stafford",    "QB",  "Georgia",           "DET", 2015),
    ("staffordm-01", "Matthew Stafford",    "QB",  "Georgia",           "DET", 2016),
    ("staffordm-01", "Matthew Stafford",    "QB",  "Georgia",           "DET", 2017),
    ("staffordm-01", "Matthew Stafford",    "QB",  "Georgia",           "DET", 2018),
    ("staffordm-01", "Matthew Stafford",    "QB",  "Georgia",           "DET", 2019),
    ("staffordm-01", "Matthew Stafford",    "QB",  "Georgia",           "DET", 2020),
    ("staffordm-01", "Matthew Stafford",    "QB",  "Georgia",           "RAM", 2021),  # Bridge DET→RAM
    ("staffordm-01", "Matthew Stafford",    "QB",  "Georgia",           "RAM", 2022),
    ("kuppc-01",     "Cooper Kupp",         "WR",  "Eastern Washington","RAM", 2017),
    ("kuppc-01",     "Cooper Kupp",         "WR",  "Eastern Washington","RAM", 2018),
    ("kuppc-01",     "Cooper Kupp",         "WR",  "Eastern Washington","RAM", 2019),
    ("kuppc-01",     "Cooper Kupp",         "WR",  "Eastern Washington","RAM", 2020),
    ("kuppc-01",     "Cooper Kupp",         "WR",  "Eastern Washington","RAM", 2021),
    ("kuppc-01",     "Cooper Kupp",         "WR",  "Eastern Washington","RAM", 2022),
    ("kuppc-01",     "Cooper Kupp",         "WR",  "Eastern Washington","RAM", 2023),
    ("donalda-01",   "Aaron Donald",        "DT",  "Pittsburgh",        "RAM", 2014),
    ("donalda-01",   "Aaron Donald",        "DT",  "Pittsburgh",        "RAM", 2015),
    ("donalda-01",   "Aaron Donald",        "DT",  "Pittsburgh",        "RAM", 2016),
    ("donalda-01",   "Aaron Donald",        "DT",  "Pittsburgh",        "RAM", 2017),
    ("donalda-01",   "Aaron Donald",        "DT",  "Pittsburgh",        "RAM", 2018),
    ("donalda-01",   "Aaron Donald",        "DT",  "Pittsburgh",        "RAM", 2019),
    ("donalda-01",   "Aaron Donald",        "DT",  "Pittsburgh",        "RAM", 2020),
    ("donalda-01",   "Aaron Donald",        "DT",  "Pittsburgh",        "RAM", 2021),
    ("donalda-01",   "Aaron Donald",        "DT",  "Pittsburgh",        "RAM", 2022),
    ("ramseyj-01",   "Jalen Ramsey",        "CB",  "Florida State",     "JAX", 2016),
    ("ramseyj-01",   "Jalen Ramsey",        "CB",  "Florida State",     "JAX", 2017),
    ("ramseyj-01",   "Jalen Ramsey",        "CB",  "Florida State",     "JAX", 2018),
    ("ramseyj-01",   "Jalen Ramsey",        "CB",  "Florida State",     "JAX", 2019),
    ("ramseyj-01",   "Jalen Ramsey",        "CB",  "Florida State",     "RAM", 2019),
    ("ramseyj-01",   "Jalen Ramsey",        "CB",  "Florida State",     "RAM", 2020),
    ("ramseyj-01",   "Jalen Ramsey",        "CB",  "Florida State",     "RAM", 2021),
    ("ramseyj-01",   "Jalen Ramsey",        "CB",  "Florida State",     "RAM", 2022),
    ("ramseyj-01",   "Jalen Ramsey",        "CB",  "Florida State",     "MIA", 2023),  # Bridge RAM→MIA
    # Zac Taylor (McVay disciple) → Cincinnati Bengals
    ("burrowj-01",   "Joe Burrow",          "QB",  "LSU",               "CIN", 2020),
    ("burrowj-01",   "Joe Burrow",          "QB",  "LSU",               "CIN", 2021),
    ("burrowj-01",   "Joe Burrow",          "QB",  "LSU",               "CIN", 2022),
    ("burrowj-01",   "Joe Burrow",          "QB",  "LSU",               "CIN", 2023),
    ("chaseja-01",   "Ja'Marr Chase",       "WR",  "LSU",               "CIN", 2021),   # LSU → same as Burrow
    ("chaseja-01",   "Ja'Marr Chase",       "WR",  "LSU",               "CIN", 2022),
    ("chaseja-01",   "Ja'Marr Chase",       "WR",  "LSU",               "CIN", 2023),
    ("higginst-01",  "Tee Higgins",         "WR",  "Clemson",           "CIN", 2020),
    ("higginst-01",  "Tee Higgins",         "WR",  "Clemson",           "CIN", 2021),
    ("higginst-01",  "Tee Higgins",         "WR",  "Clemson",           "CIN", 2022),
    ("higginst-01",  "Tee Higgins",         "WR",  "Clemson",           "CIN", 2023),
    ("mixonj-01",    "Joe Mixon",           "RB",  "Oklahoma",          "CIN", 2017),
    ("mixonj-01",    "Joe Mixon",           "RB",  "Oklahoma",          "CIN", 2018),
    ("mixonj-01",    "Joe Mixon",           "RB",  "Oklahoma",          "CIN", 2019),
    ("mixonj-01",    "Joe Mixon",           "RB",  "Oklahoma",          "CIN", 2020),
    ("mixonj-01",    "Joe Mixon",           "RB",  "Oklahoma",          "CIN", 2021),
    ("mixonj-01",    "Joe Mixon",           "RB",  "Oklahoma",          "CIN", 2022),
    ("mixonj-01",    "Joe Mixon",           "RB",  "Oklahoma",          "HOU", 2023),

    # ─── KYLE SHANAHAN — SAN FRANCISCO 49ERS ────────────────────────────────
    ("kittleg-01",   "George Kittle",       "TE",  "Iowa",              "SFO", 2017),
    ("kittleg-01",   "George Kittle",       "TE",  "Iowa",              "SFO", 2018),
    ("kittleg-01",   "George Kittle",       "TE",  "Iowa",              "SFO", 2019),
    ("kittleg-01",   "George Kittle",       "TE",  "Iowa",              "SFO", 2020),
    ("kittleg-01",   "George Kittle",       "TE",  "Iowa",              "SFO", 2021),
    ("kittleg-01",   "George Kittle",       "TE",  "Iowa",              "SFO", 2022),
    ("kittleg-01",   "George Kittle",       "TE",  "Iowa",              "SFO", 2023),
    ("purdyb-01",    "Brock Purdy",         "QB",  "Iowa State",        "SFO", 2022),
    ("purdyb-01",    "Brock Purdy",         "QB",  "Iowa State",        "SFO", 2023),
    ("mccaffreyc-01","Christian McCaffrey", "RB",  "Stanford",          "CAR", 2017),
    ("mccaffreyc-01","Christian McCaffrey", "RB",  "Stanford",          "CAR", 2018),
    ("mccaffreyc-01","Christian McCaffrey", "RB",  "Stanford",          "CAR", 2019),
    ("mccaffreyc-01","Christian McCaffrey", "RB",  "Stanford",          "CAR", 2020),
    ("mccaffreyc-01","Christian McCaffrey", "RB",  "Stanford",          "CAR", 2021),
    ("mccaffreyc-01","Christian McCaffrey", "RB",  "Stanford",          "SFO", 2022),  # Bridge CAR→SFO
    ("mccaffreyc-01","Christian McCaffrey", "RB",  "Stanford",          "SFO", 2023),
    ("samuelD-01",   "Deebo Samuel",        "WR",  "South Carolina",    "SFO", 2019),
    ("samuelD-01",   "Deebo Samuel",        "WR",  "South Carolina",    "SFO", 2020),
    ("samuelD-01",   "Deebo Samuel",        "WR",  "South Carolina",    "SFO", 2021),
    ("samuelD-01",   "Deebo Samuel",        "WR",  "South Carolina",    "SFO", 2022),
    ("samuelD-01",   "Deebo Samuel",        "WR",  "South Carolina",    "SFO", 2023),
    ("aiyukb-01",    "Brandon Aiyuk",       "WR",  "Arizona State",     "SFO", 2020),
    ("aiyukb-01",    "Brandon Aiyuk",       "WR",  "Arizona State",     "SFO", 2021),
    ("aiyukb-01",    "Brandon Aiyuk",       "WR",  "Arizona State",     "SFO", 2022),
    ("aiyukb-01",    "Brandon Aiyuk",       "WR",  "Arizona State",     "SFO", 2023),
    ("warnerf-01",   "Fred Warner",         "LB",  "BYU",               "SFO", 2018),
    ("warnerf-01",   "Fred Warner",         "LB",  "BYU",               "SFO", 2019),
    ("warnerf-01",   "Fred Warner",         "LB",  "BYU",               "SFO", 2020),
    ("warnerf-01",   "Fred Warner",         "LB",  "BYU",               "SFO", 2021),
    ("warnerf-01",   "Fred Warner",         "LB",  "BYU",               "SFO", 2022),
    ("warnerf-01",   "Fred Warner",         "LB",  "BYU",               "SFO", 2023),
    # Kyle Shanahan also was OC in Atlanta (bridging to earlier eras)
    ("ryanm-01",     "Matt Ryan",           "QB",  "Boston College",    "ATL", 2008),
    ("ryanm-01",     "Matt Ryan",           "QB",  "Boston College",    "ATL", 2012),
    ("ryanm-01",     "Matt Ryan",           "QB",  "Boston College",    "ATL", 2013),
    ("ryanm-01",     "Matt Ryan",           "QB",  "Boston College",    "ATL", 2014),
    ("ryanm-01",     "Matt Ryan",           "QB",  "Boston College",    "ATL", 2015),
    ("ryanm-01",     "Matt Ryan",           "QB",  "Boston College",    "ATL", 2016),
    ("ryanm-01",     "Matt Ryan",           "QB",  "Boston College",    "ATL", 2017),
    ("ryanm-01",     "Matt Ryan",           "QB",  "Boston College",    "IND", 2022),

    # ─── JOHN HARBAUGH — BALTIMORE RAVENS ───────────────────────────────────
    ("flaccoj-01",   "Joe Flacco",          "QB",  "Delaware",          "RAV", 2008),
    ("flaccoj-01",   "Joe Flacco",          "QB",  "Delaware",          "RAV", 2009),
    ("flaccoj-01",   "Joe Flacco",          "QB",  "Delaware",          "RAV", 2010),
    ("flaccoj-01",   "Joe Flacco",          "QB",  "Delaware",          "RAV", 2011),
    ("flaccoj-01",   "Joe Flacco",          "QB",  "Delaware",          "RAV", 2012),
    ("flaccoj-01",   "Joe Flacco",          "QB",  "Delaware",          "RAV", 2013),
    ("flaccoj-01",   "Joe Flacco",          "QB",  "Delaware",          "RAV", 2014),
    ("flaccoj-01",   "Joe Flacco",          "QB",  "Delaware",          "RAV", 2015),
    ("flaccoj-01",   "Joe Flacco",          "QB",  "Delaware",          "RAV", 2016),
    ("flaccoj-01",   "Joe Flacco",          "QB",  "Delaware",          "RAV", 2017),
    ("flaccoj-01",   "Joe Flacco",          "QB",  "Delaware",          "RAV", 2018),
    ("jacksonl-01",  "Lamar Jackson",       "QB",  "Louisville",        "RAV", 2018),
    ("jacksonl-01",  "Lamar Jackson",       "QB",  "Louisville",        "RAV", 2019),
    ("jacksonl-01",  "Lamar Jackson",       "QB",  "Louisville",        "RAV", 2020),
    ("jacksonl-01",  "Lamar Jackson",       "QB",  "Louisville",        "RAV", 2021),
    ("jacksonl-01",  "Lamar Jackson",       "QB",  "Louisville",        "RAV", 2022),
    ("jacksonl-01",  "Lamar Jackson",       "QB",  "Louisville",        "RAV", 2023),
    ("andrewsm-01",  "Mark Andrews",        "TE",  "Oklahoma",          "RAV", 2018),
    ("andrewsm-01",  "Mark Andrews",        "TE",  "Oklahoma",          "RAV", 2019),
    ("andrewsm-01",  "Mark Andrews",        "TE",  "Oklahoma",          "RAV", 2020),
    ("andrewsm-01",  "Mark Andrews",        "TE",  "Oklahoma",          "RAV", 2021),
    ("andrewsm-01",  "Mark Andrews",        "TE",  "Oklahoma",          "RAV", 2022),
    ("andrewsm-01",  "Mark Andrews",        "TE",  "Oklahoma",          "RAV", 2023),
    ("tuckerj-01",   "Justin Tucker",       "K",   "Texas",             "RAV", 2012),
    ("tuckerj-01",   "Justin Tucker",       "K",   "Texas",             "RAV", 2015),
    ("tuckerj-01",   "Justin Tucker",       "K",   "Texas",             "RAV", 2018),
    ("tuckerj-01",   "Justin Tucker",       "K",   "Texas",             "RAV", 2021),
    ("tuckerj-01",   "Justin Tucker",       "K",   "Texas",             "RAV", 2023),
    ("henryd-01",    "Derrick Henry",       "RB",  "Alabama",           "TEN", 2016),
    ("henryd-01",    "Derrick Henry",       "RB",  "Alabama",           "TEN", 2017),
    ("henryd-01",    "Derrick Henry",       "RB",  "Alabama",           "TEN", 2018),
    ("henryd-01",    "Derrick Henry",       "RB",  "Alabama",           "TEN", 2019),
    ("henryd-01",    "Derrick Henry",       "RB",  "Alabama",           "TEN", 2020),
    ("henryd-01",    "Derrick Henry",       "RB",  "Alabama",           "TEN", 2021),
    ("henryd-01",    "Derrick Henry",       "RB",  "Alabama",           "RAV", 2024),  # Bridge TEN→RAV

    # ─── MIAMI DOLPHINS — Mike McDaniel (Shanahan disciple) ─────────────────
    ("tuaw-01",      "Tua Tagovailoa",      "QB",  "Alabama",           "MIA", 2020),
    ("tuaw-01",      "Tua Tagovailoa",      "QB",  "Alabama",           "MIA", 2021),
    ("tuaw-01",      "Tua Tagovailoa",      "QB",  "Alabama",           "MIA", 2022),
    ("tuaw-01",      "Tua Tagovailoa",      "QB",  "Alabama",           "MIA", 2023),
    ("waddlej-01",   "Jaylen Waddle",       "WR",  "Alabama",           "MIA", 2021),  # Alabama pipeline!
    ("waddlej-01",   "Jaylen Waddle",       "WR",  "Alabama",           "MIA", 2022),
    ("waddlej-01",   "Jaylen Waddle",       "WR",  "Alabama",           "MIA", 2023),
    # Note: Tua, Waddle, Hill all Alabama → MIA

    # ─── GREEN BAY PACKERS — Matt LaFleur (Shanahan disciple as OC) ─────────
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2005),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2006),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2007),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2008),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2009),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2010),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2011),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2012),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2013),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2014),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2015),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2016),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2017),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2018),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2019),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2020),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2021),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "GNB", 2022),
    ("rodgersa-01",  "Aaron Rodgers",       "QB",  "California",        "NYJ", 2023),  # Bridge GNB→NYJ
    ("adamsd-01",    "Davante Adams",       "WR",  "Fresno State",      "GNB", 2014),
    ("adamsd-01",    "Davante Adams",       "WR",  "Fresno State",      "GNB", 2015),
    ("adamsd-01",    "Davante Adams",       "WR",  "Fresno State",      "GNB", 2016),
    ("adamsd-01",    "Davante Adams",       "WR",  "Fresno State",      "GNB", 2017),
    ("adamsd-01",    "Davante Adams",       "WR",  "Fresno State",      "GNB", 2018),
    ("adamsd-01",    "Davante Adams",       "WR",  "Fresno State",      "GNB", 2019),
    ("adamsd-01",    "Davante Adams",       "WR",  "Fresno State",      "GNB", 2020),
    ("adamsd-01",    "Davante Adams",       "WR",  "Fresno State",      "GNB", 2021),
    ("adamsd-01",    "Davante Adams",       "WR",  "Fresno State",      "RAI", 2022),  # Bridge GNB→RAI
    ("adamsd-01",    "Davante Adams",       "WR",  "Fresno State",      "RAI", 2023),
    ("jonesaa-01",   "Aaron Jones",         "RB",  "UTEP",              "GNB", 2017),
    ("jonesaa-01",   "Aaron Jones",         "RB",  "UTEP",              "GNB", 2018),
    ("jonesaa-01",   "Aaron Jones",         "RB",  "UTEP",              "GNB", 2019),
    ("jonesaa-01",   "Aaron Jones",         "RB",  "UTEP",              "GNB", 2020),
    ("jonesaa-01",   "Aaron Jones",         "RB",  "UTEP",              "GNB", 2021),
    ("jonesaa-01",   "Aaron Jones",         "RB",  "UTEP",              "GNB", 2022),
    ("jonesaa-01",   "Aaron Jones",         "RB",  "UTEP",              "MIN", 2023),

    # ─── PEYTON MANNING ERA (bridges older eras) ────────────────────────────
    ("manningp-01",  "Peyton Manning",      "QB",  "Tennessee",         "CLT", 1998),
    ("manningp-01",  "Peyton Manning",      "QB",  "Tennessee",         "CLT", 2003),
    ("manningp-01",  "Peyton Manning",      "QB",  "Tennessee",         "CLT", 2004),
    ("manningp-01",  "Peyton Manning",      "QB",  "Tennessee",         "CLT", 2005),
    ("manningp-01",  "Peyton Manning",      "QB",  "Tennessee",         "CLT", 2006),
    ("manningp-01",  "Peyton Manning",      "QB",  "Tennessee",         "CLT", 2007),
    ("manningp-01",  "Peyton Manning",      "QB",  "Tennessee",         "CLT", 2008),
    ("manningp-01",  "Peyton Manning",      "QB",  "Tennessee",         "CLT", 2009),
    ("manningp-01",  "Peyton Manning",      "QB",  "Tennessee",         "CLT", 2010),
    ("manningp-01",  "Peyton Manning",      "QB",  "Tennessee",         "DEN", 2012),
    ("manningp-01",  "Peyton Manning",      "QB",  "Tennessee",         "DEN", 2013),
    ("manningp-01",  "Peyton Manning",      "QB",  "Tennessee",         "DEN", 2014),
    ("manningp-01",  "Peyton Manning",      "QB",  "Tennessee",         "DEN", 2015),
    ("wayner-01",    "Reggie Wayne",        "WR",  "Miami (FL)",        "CLT", 2001),
    ("wayner-01",    "Reggie Wayne",        "WR",  "Miami (FL)",        "CLT", 2004),
    ("wayner-01",    "Reggie Wayne",        "WR",  "Miami (FL)",        "CLT", 2006),
    ("wayner-01",    "Reggie Wayne",        "WR",  "Miami (FL)",        "CLT", 2008),
    ("wayner-01",    "Reggie Wayne",        "WR",  "Miami (FL)",        "CLT", 2010),
    ("wayner-01",    "Reggie Wayne",        "WR",  "Miami (FL)",        "CLT", 2012),
    ("millerv-01",   "Von Miller",          "LB",  "Texas A&M",         "DEN", 2011),
    ("millerv-01",   "Von Miller",          "LB",  "Texas A&M",         "DEN", 2013),
    ("millerv-01",   "Von Miller",          "LB",  "Texas A&M",         "DEN", 2015),
    ("millerv-01",   "Von Miller",          "LB",  "Texas A&M",         "DEN", 2016),
    ("millerv-01",   "Von Miller",          "LB",  "Texas A&M",         "DEN", 2019),
    ("millerv-01",   "Von Miller",          "LB",  "Texas A&M",         "RAM", 2021),  # Bridge DEN→RAM
    ("millerv-01",   "Von Miller",          "LB",  "Texas A&M",         "RAM", 2022),
    ("thomasd-01",   "Demaryius Thomas",    "WR",  "Georgia Tech",      "DEN", 2010),
    ("thomasd-01",   "Demaryius Thomas",    "WR",  "Georgia Tech",      "DEN", 2012),
    ("thomasd-01",   "Demaryius Thomas",    "WR",  "Georgia Tech",      "DEN", 2013),
    ("thomasd-01",   "Demaryius Thomas",    "WR",  "Georgia Tech",      "DEN", 2015),
    ("thomasd-01",   "Demaryius Thomas",    "WR",  "Georgia Tech",      "DEN", 2017),
    ("thomasd-01",   "Demaryius Thomas",    "WR",  "Georgia Tech",      "HOU", 2018),

    # ─── STEELERS DYNASTY ────────────────────────────────────────────────────
    ("roethlisbergb-01","Ben Roethlisberger","QB", "Miami (OH)",        "PIT", 2004),
    ("roethlisbergb-01","Ben Roethlisberger","QB", "Miami (OH)",        "PIT", 2006),
    ("roethlisbergb-01","Ben Roethlisberger","QB", "Miami (OH)",        "PIT", 2008),
    ("roethlisbergb-01","Ben Roethlisberger","QB", "Miami (OH)",        "PIT", 2010),
    ("roethlisbergb-01","Ben Roethlisberger","QB", "Miami (OH)",        "PIT", 2015),
    ("roethlisbergb-01","Ben Roethlisberger","QB", "Miami (OH)",        "PIT", 2018),
    ("roethlisbergb-01","Ben Roethlisberger","QB", "Miami (OH)",        "PIT", 2021),
    ("brownant-01",  "Antonio Brown",       "WR",  "Central Michigan",  "PIT", 2010),
    ("brownant-01",  "Antonio Brown",       "WR",  "Central Michigan",  "PIT", 2011),
    ("brownant-01",  "Antonio Brown",       "WR",  "Central Michigan",  "PIT", 2012),
    ("brownant-01",  "Antonio Brown",       "WR",  "Central Michigan",  "PIT", 2013),
    ("brownant-01",  "Antonio Brown",       "WR",  "Central Michigan",  "PIT", 2014),
    ("brownant-01",  "Antonio Brown",       "WR",  "Central Michigan",  "PIT", 2015),
    ("brownant-01",  "Antonio Brown",       "WR",  "Central Michigan",  "PIT", 2016),
    ("brownant-01",  "Antonio Brown",       "WR",  "Central Michigan",  "PIT", 2017),
    ("brownant-01",  "Antonio Brown",       "WR",  "Central Michigan",  "PIT", 2018),
    ("brownant-01",  "Antonio Brown",       "WR",  "Central Michigan",  "RAI", 2019),  # Bridge PIT→RAI
    ("brownant-01",  "Antonio Brown",       "WR",  "Central Michigan",  "TAM", 2020),  # Bridge RAI→TAM
    ("brownant-01",  "Antonio Brown",       "WR",  "Central Michigan",  "TAM", 2021),
    ("bellel-01",    "Le'Veon Bell",        "RB",  "Michigan State",    "PIT", 2013),
    ("bellel-01",    "Le'Veon Bell",        "RB",  "Michigan State",    "PIT", 2014),
    ("bellel-01",    "Le'Veon Bell",        "RB",  "Michigan State",    "PIT", 2015),
    ("bellel-01",    "Le'Veon Bell",        "RB",  "Michigan State",    "PIT", 2016),
    ("bellel-01",    "Le'Veon Bell",        "RB",  "Michigan State",    "PIT", 2017),
    ("bellel-01",    "Le'Veon Bell",        "RB",  "Michigan State",    "NYJ", 2019),  # Bridge PIT→NYJ
    ("bellel-01",    "Le'Veon Bell",        "RB",  "Michigan State",    "KAN", 2020),  # Bridge NYJ→KAN
    ("wattjj-01",    "J.J. Watt",           "DE",  "Wisconsin",         "HOU", 2011),
    ("wattjj-01",    "J.J. Watt",           "DE",  "Wisconsin",         "HOU", 2013),
    ("wattjj-01",    "J.J. Watt",           "DE",  "Wisconsin",         "HOU", 2015),
    ("wattjj-01",    "J.J. Watt",           "DE",  "Wisconsin",         "HOU", 2018),
    ("wattjj-01",    "J.J. Watt",           "DE",  "Wisconsin",         "HOU", 2020),
    ("wattjj-01",    "J.J. Watt",           "DE",  "Wisconsin",         "ARI", 2021),  # Bridge HOU→ARI
    ("wattjj-01",    "J.J. Watt",           "DE",  "Wisconsin",         "ARI", 2022),

    # ─── RUSSELL WILSON ERA — SEAHAWKS / BRONCOS ────────────────────────────
    ("wilsonr-01",   "Russell Wilson",      "QB",  "Wisconsin",         "SEA", 2012),
    ("wilsonr-01",   "Russell Wilson",      "QB",  "Wisconsin",         "SEA", 2013),
    ("wilsonr-01",   "Russell Wilson",      "QB",  "Wisconsin",         "SEA", 2014),
    ("wilsonr-01",   "Russell Wilson",      "QB",  "Wisconsin",         "SEA", 2015),
    ("wilsonr-01",   "Russell Wilson",      "QB",  "Wisconsin",         "SEA", 2016),
    ("wilsonr-01",   "Russell Wilson",      "QB",  "Wisconsin",         "SEA", 2017),
    ("wilsonr-01",   "Russell Wilson",      "QB",  "Wisconsin",         "SEA", 2018),
    ("wilsonr-01",   "Russell Wilson",      "QB",  "Wisconsin",         "SEA", 2019),
    ("wilsonr-01",   "Russell Wilson",      "QB",  "Wisconsin",         "SEA", 2020),
    ("wilsonr-01",   "Russell Wilson",      "QB",  "Wisconsin",         "SEA", 2021),
    ("wilsonr-01",   "Russell Wilson",      "QB",  "Wisconsin",         "DEN", 2022),  # Bridge SEA→DEN
    ("wilsonr-01",   "Russell Wilson",      "QB",  "Wisconsin",         "DEN", 2023),
    ("metcalfd-01",  "DK Metcalf",          "WR",  "Ole Miss",          "SEA", 2019),
    ("metcalfd-01",  "DK Metcalf",          "WR",  "Ole Miss",          "SEA", 2020),
    ("metcalfd-01",  "DK Metcalf",          "WR",  "Ole Miss",          "SEA", 2021),
    ("metcalfd-01",  "DK Metcalf",          "WR",  "Ole Miss",          "SEA", 2022),
    ("metcalfd-01",  "DK Metcalf",          "WR",  "Ole Miss",          "SEA", 2023),
    ("lockettty-01", "Tyler Lockett",       "WR",  "Kansas State",      "SEA", 2015),
    ("lockettty-01", "Tyler Lockett",       "WR",  "Kansas State",      "SEA", 2017),
    ("lockettty-01", "Tyler Lockett",       "WR",  "Kansas State",      "SEA", 2019),
    ("lockettty-01", "Tyler Lockett",       "WR",  "Kansas State",      "SEA", 2021),
    ("lockettty-01", "Tyler Lockett",       "WR",  "Kansas State",      "SEA", 2023),
]

coach_data = [
    # Bill Belichick — New England Patriots
    ("NWE", 2001, "Bill Belichick"), ("NWE", 2002, "Bill Belichick"),
    ("NWE", 2003, "Bill Belichick"), ("NWE", 2004, "Bill Belichick"),
    ("NWE", 2005, "Bill Belichick"), ("NWE", 2006, "Bill Belichick"),
    ("NWE", 2007, "Bill Belichick"), ("NWE", 2008, "Bill Belichick"),
    ("NWE", 2009, "Bill Belichick"), ("NWE", 2010, "Bill Belichick"),
    ("NWE", 2011, "Bill Belichick"), ("NWE", 2012, "Bill Belichick"),
    ("NWE", 2013, "Bill Belichick"), ("NWE", 2014, "Bill Belichick"),
    ("NWE", 2015, "Bill Belichick"), ("NWE", 2016, "Bill Belichick"),
    ("NWE", 2017, "Bill Belichick"), ("NWE", 2018, "Bill Belichick"),
    ("NWE", 2019, "Bill Belichick"), ("NWE", 2020, "Bill Belichick"),
    ("NWE", 2021, "Bill Belichick"), ("NWE", 2022, "Bill Belichick"),
    ("NWE", 2023, "Bill Belichick"),
    # Belichick disciples
    ("RAI", 2022, "Josh McDaniels"), ("RAI", 2023, "Josh McDaniels"),
    ("RAI", 2019, "Jon Gruden"),     ("RAI", 2020, "Jon Gruden"),
    ("RAI", 2021, "Jon Gruden"),
    ("RAI", 2014, "Tony Sparano"),   ("RAI", 2015, "Jack Del Rio"),
    ("RAI", 2016, "Jack Del Rio"),   ("RAI", 2017, "Jack Del Rio"),
    ("RAI", 2018, "Jon Gruden"),
    ("DET", 2018, "Matt Patricia"),  ("DET", 2019, "Matt Patricia"),
    ("DET", 2020, "Matt Patricia"),
    # Bruce Arians / Todd Bowles — Tampa Bay
    ("TAM", 2014, "Lovie Smith"),    ("TAM", 2015, "Lovie Smith"),
    ("TAM", 2016, "Dirk Koetter"),   ("TAM", 2017, "Dirk Koetter"),
    ("TAM", 2018, "Dirk Koetter"),   ("TAM", 2019, "Bruce Arians"),
    ("TAM", 2020, "Bruce Arians"),   ("TAM", 2021, "Bruce Arians"),
    ("TAM", 2022, "Todd Bowles"),    ("TAM", 2023, "Todd Bowles"),
    # Andy Reid — Kansas City
    ("KAN", 2013, "Andy Reid"), ("KAN", 2014, "Andy Reid"),
    ("KAN", 2015, "Andy Reid"), ("KAN", 2016, "Andy Reid"),
    ("KAN", 2017, "Andy Reid"), ("KAN", 2018, "Andy Reid"),
    ("KAN", 2019, "Andy Reid"), ("KAN", 2020, "Andy Reid"),
    ("KAN", 2021, "Andy Reid"), ("KAN", 2022, "Andy Reid"),
    ("KAN", 2023, "Andy Reid"),
    # Andy Reid disciple - Nick Sirianni — Philadelphia
    ("PHI", 2021, "Nick Sirianni"), ("PHI", 2022, "Nick Sirianni"),
    ("PHI", 2023, "Nick Sirianni"),
    # Sean McVay — LA Rams
    ("RAM", 2017, "Sean McVay"), ("RAM", 2018, "Sean McVay"),
    ("RAM", 2019, "Sean McVay"), ("RAM", 2020, "Sean McVay"),
    ("RAM", 2021, "Sean McVay"), ("RAM", 2022, "Sean McVay"),
    ("RAM", 2023, "Sean McVay"),
    # Earlier RAM coaches (before McVay took Goff)
    ("RAM", 2009, "Steve Spagnuolo"), ("RAM", 2010, "Steve Spagnuolo"),
    ("RAM", 2016, "Jeff Fisher"),
    # Zac Taylor (McVay disciple) — Cincinnati
    ("CIN", 2019, "Zac Taylor"), ("CIN", 2020, "Zac Taylor"),
    ("CIN", 2021, "Zac Taylor"), ("CIN", 2022, "Zac Taylor"),
    ("CIN", 2023, "Zac Taylor"),
    # Kyle Shanahan — San Francisco
    ("SFO", 2017, "Kyle Shanahan"), ("SFO", 2018, "Kyle Shanahan"),
    ("SFO", 2019, "Kyle Shanahan"), ("SFO", 2020, "Kyle Shanahan"),
    ("SFO", 2021, "Kyle Shanahan"), ("SFO", 2022, "Kyle Shanahan"),
    ("SFO", 2023, "Kyle Shanahan"),
    # Kyle Shanahan was OC in Atlanta under Dan Quinn
    ("ATL", 2015, "Dan Quinn"),     ("ATL", 2016, "Dan Quinn"),
    ("ATL", 2017, "Dan Quinn"),     ("ATL", 2018, "Dan Quinn"),
    # Mike McDaniel (Shanahan disciple) — Miami
    ("MIA", 2022, "Mike McDaniel"), ("MIA", 2023, "Mike McDaniel"),
    # Earlier MIA
    ("MIA", 2019, "Brian Flores"),  ("MIA", 2020, "Brian Flores"),
    ("MIA", 2021, "Brian Flores"),
    # Matt LaFleur (Shanahan disciple) — Green Bay
    ("GNB", 2019, "Matt LaFleur"), ("GNB", 2020, "Matt LaFleur"),
    ("GNB", 2021, "Matt LaFleur"), ("GNB", 2022, "Matt LaFleur"),
    ("GNB", 2023, "Matt LaFleur"),
    # Earlier GNB
    ("GNB", 2006, "Mike McCarthy"), ("GNB", 2010, "Mike McCarthy"),
    ("GNB", 2012, "Mike McCarthy"), ("GNB", 2014, "Mike McCarthy"),
    ("GNB", 2016, "Mike McCarthy"), ("GNB", 2018, "Mike McCarthy"),
    # John Harbaugh — Baltimore
    ("RAV", 2008, "John Harbaugh"), ("RAV", 2010, "John Harbaugh"),
    ("RAV", 2012, "John Harbaugh"), ("RAV", 2014, "John Harbaugh"),
    ("RAV", 2016, "John Harbaugh"), ("RAV", 2018, "John Harbaugh"),
    ("RAV", 2019, "John Harbaugh"), ("RAV", 2020, "John Harbaugh"),
    ("RAV", 2021, "John Harbaugh"), ("RAV", 2022, "John Harbaugh"),
    ("RAV", 2023, "John Harbaugh"), ("RAV", 2024, "John Harbaugh"),
    # Denver Broncos
    ("DEN", 2011, "John Fox"),      ("DEN", 2012, "John Fox"),
    ("DEN", 2013, "John Fox"),      ("DEN", 2014, "John Fox"),
    ("DEN", 2015, "Gary Kubiak"),   ("DEN", 2016, "Gary Kubiak"),
    ("DEN", 2017, "Vance Joseph"),  ("DEN", 2018, "Vance Joseph"),
    ("DEN", 2019, "Vic Fangio"),    ("DEN", 2020, "Vic Fangio"),
    ("DEN", 2021, "Vic Fangio"),    ("DEN", 2022, "Nathaniel Hackett"),
    ("DEN", 2023, "Sean Payton"),
    # Indianapolis Colts
    ("CLT", 1998, "Jim Mora"),      ("CLT", 2002, "Tony Dungy"),
    ("CLT", 2003, "Tony Dungy"),    ("CLT", 2004, "Tony Dungy"),
    ("CLT", 2005, "Tony Dungy"),    ("CLT", 2006, "Tony Dungy"),
    ("CLT", 2007, "Tony Dungy"),    ("CLT", 2008, "Tony Dungy"),
    ("CLT", 2009, "Jim Caldwell"),  ("CLT", 2010, "Jim Caldwell"),
    ("CLT", 2012, "Chuck Pagano"),  ("CLT", 2022, "Frank Reich"),
    # Pittsburgh Steelers
    ("PIT", 2004, "Bill Cowher"),   ("PIT", 2006, "Bill Cowher"),
    ("PIT", 2007, "Mike Tomlin"),   ("PIT", 2008, "Mike Tomlin"),
    ("PIT", 2010, "Mike Tomlin"),   ("PIT", 2011, "Mike Tomlin"),
    ("PIT", 2013, "Mike Tomlin"),   ("PIT", 2015, "Mike Tomlin"),
    ("PIT", 2017, "Mike Tomlin"),   ("PIT", 2018, "Mike Tomlin"),
    ("PIT", 2021, "Mike Tomlin"),
    # Houston Texans
    ("HOU", 2011, "Gary Kubiak"),   ("HOU", 2013, "Bill O'Brien"),
    ("HOU", 2018, "Bill O'Brien"),  ("HOU", 2020, "Bill O'Brien"),
    ("HOU", 2023, "DeMeco Ryans"),
    # Tennessee Titans
    ("TEN", 2016, "Mike Mularkey"), ("TEN", 2019, "Mike Vrabel"),
    ("TEN", 2020, "Mike Vrabel"),   ("TEN", 2021, "Mike Vrabel"),
    # Jacksonville
    ("JAX", 2016, "Gus Bradley"),   ("JAX", 2018, "Doug Marrone"),
    # Detroit Lions
    ("DET", 2009, "Jim Schwartz"),  ("DET", 2013, "Jim Caldwell"),
    ("DET", 2014, "Jim Caldwell"),  ("DET", 2016, "Jim Caldwell"),
    ("DET", 2021, "Dan Campbell"),  ("DET", 2022, "Dan Campbell"),
    ("DET", 2023, "Dan Campbell"),
    # New York Jets
    ("NYJ", 2019, "Adam Gase"),     ("NYJ", 2022, "Robert Saleh"),
    ("NYJ", 2023, "Robert Saleh"),
    # New York Giants
    ("NYG", 2023, "Brian Daboll"),
    # Seattle Seahawks
    ("SEA", 2010, "Pete Carroll"),  ("SEA", 2012, "Pete Carroll"),
    ("SEA", 2013, "Pete Carroll"),  ("SEA", 2015, "Pete Carroll"),
    ("SEA", 2017, "Pete Carroll"),  ("SEA", 2019, "Pete Carroll"),
    ("SEA", 2021, "Pete Carroll"),  ("SEA", 2023, "Pete Carroll"),
    # Arizona Cardinals
    ("ARI", 2013, "Bruce Arians"),  ("ARI", 2017, "Bruce Arians"),
    ("ARI", 2021, "Kliff Kingsbury"), ("ARI", 2022, "Kliff Kingsbury"),
    # Washington
    ("WAS", 2018, "Jay Gruden"),
    # Carolina Panthers
    ("CAR", 2017, "Ron Rivera"),    ("CAR", 2019, "Ron Rivera"),
    ("CAR", 2021, "Matt Rhule"),    ("CAR", 2022, "Matt Rhule"),
]

import os
os.makedirs('data', exist_ok=True)

df_r = pd.DataFrame(roster_data, columns=["player_id","name","position","college","team","year"])
df_c = pd.DataFrame(coach_data,  columns=["team","year","head_coach"])

df_r.to_csv('data/rosters.csv', index=False)
df_c.to_csv('data/coaches.csv', index=False)
print(f"Wrote {len(df_r)} roster rows, {len(df_c)} coach rows")
print(f"Players: {df_r['player_id'].nunique()}")
print(f"Seasons: {df_r['year'].min()}-{df_r['year'].max()}")
print(f"Colleges: {df_r['college'].nunique()} unique")
